/** Category id -> display name and list of component names (as exported from nothingx-react-components) */
export const categories: { id: string; name: string; components: string[] }[] = [
  { id: 'core', name: 'Core (Clock, Date, Weather, Battery…)', components: ['Clock', 'DateWidget', 'Weather', 'MonitorRAM', 'MonitorStorage', 'Battery', 'Music', 'Quotes', 'Calendar', 'Photos', 'CalendarEvent'] },
  { id: 'system', name: 'System & Hardware', components: ['MonitorCPU', 'MonitorNetwork', 'WifiSignal', 'BluetoothStatus', 'Temperature', 'VolumeControl', 'BrightnessControl', 'FanSpeed', 'PowerMode', 'DeviceUptime'] },
  { id: 'weather', name: 'Weather & Environment', components: ['WeatherCurrent', 'WeatherForecast', 'AirQuality', 'SunriseSunset', 'MoonPhase'] },
  { id: 'time', name: 'Time & Productivity', components: ['Stopwatch', 'Timer', 'WorldClock', 'AlarmList', 'TodoList', 'NoteWidget', 'Pomodoro', 'Calculator'] },
  { id: 'network', name: 'Network & Feeds', components: ['NewsTicker', 'StockTicker', 'CryptoTracker', 'RSSFeed', 'DailyWord'] },
  { id: 'health', name: 'Health & Lifestyle', components: ['StepCounter', 'HeartRate', 'WaterIntake', 'SleepSummary', 'ScreenTime'] },
  { id: 'media', name: 'Media & Entertainment', components: ['AudioVisualizer', 'PodcastPlayer', 'RadioTuner', 'VoiceRecorder', 'MiniGameSnake'] },
  { id: 'core-ui', name: 'Core UI (Nothing Style)', components: ['DotMatrixText', 'NothingButton', 'NothingSwitch', 'DottedDivider', 'GlitchText', 'BarcodeGenerator', 'SegmentedDisplay', 'RadarScan', 'ProgressDots', 'NothingCard', 'PillBadge', 'GlitchImage'] },
  { id: 'doomsday', name: 'Doomsday / Mortality', components: ['DoomsdayClock', 'LifeCalendar', 'MortalityCountdown', 'EarthPopulation', 'CarbonPPM'] },
  { id: 'developer', name: 'Developer & Terminal', components: ['TerminalPrompt', 'GithubContributions', 'ServerPing', 'HexViewer', 'RegexTester', 'HashGenerator', 'BandwidthGraph', 'LocalhostPorts'] },
  { id: 'space', name: 'Space & Sci-Fi', components: ['ISS_Tracker', 'MarsWeather', 'SolarFlareMonitor', 'StarMap', 'PhaseOfVenus'] },
  { id: 'transport', name: 'Transport & Location', components: ['FlightTracker', 'TrainSchedule', 'Speedometer', 'Compass', 'Altimeter', 'CoordinateTracker'] },
  { id: 'smart-home', name: 'Smart Home & IoT', components: ['SmartLightToggle', 'ThermostatDial', 'DoorLockStatus', 'SecurityCameraFeed', 'PowerConsumption', 'PlantMoisture'] },
  { id: 'utility', name: 'Utility & Tools', components: ['UnitConverter', 'MorseCodeTranslator', 'Metronome', 'Leveler', 'DecibelMeter', 'RandomNumberGen', 'QRScannerUI', 'BPMTapper'] },
  { id: 'fun', name: 'Fun & Easter Eggs', components: ['ConwayGameOfLife', 'BouncingLogo', 'Magic8Ball', 'TamagotchiPet', 'FortuneCookie', 'CoinFlip', 'DiceRoll'] },
  { id: 'advanced-ui', name: 'Advanced UI', components: ['CaptchaNothing', 'LoadingDataStream', 'RedactedText', 'AudioWaveform', 'TerminalBlink'] },
  { id: 'gods', name: 'The Gods Themselves', components: ['ElectronPump', 'PositroniumLevel', 'TriadSync', 'IsotopeDecay', 'UniverseResonance', 'LunarGravity', 'PionInteraction', 'EstwaldEquation', 'ParaEnergyFeed', 'CosmicCooling'] },
  { id: 'foundation', name: 'Foundation', components: ['SeldonCrisisTimer', 'PrimeRadiant', 'PsychohistoryProb', 'EncyclopediaGalactica', 'TerminusMap', 'TrantorGlobe', 'MuleAnomaly', 'VaultHologram', 'ImperialCredit', 'MentalicsWave', 'GalacticEraClock', 'ShieldHoltzman'] },
  { id: 'robot', name: 'Robot series', components: ['ThreeLawsDiagnostic', 'PositronicBrain', 'HumanityIndex', 'RobopsychologyLog', 'SyntheticOrgan', 'WoodCarvingCNC', 'AsimovOverride', 'RobotSerialID', 'BatteryDecades', 'LogicLoopWarning'] },
  { id: 'dune', name: 'Dune', components: ['StillsuitWaterLevel', 'SandwormSeismograph', 'SpiceMelangeTrend', 'GomJabbarTest', 'GuildNavigatorPath', 'ThumperMetronome', 'BeneGesseritVoice', 'ArrakisSunCompass', 'OrnithopterWings', 'FremenPopulation', 'CoriolisStormRadar', 'WaterOfLife'] },
  { id: 'scifi-meta', name: 'Sci-Fi Meta', components: ['CryoPodMonitor', 'HyperspaceJump', 'TachyonComm', 'GeneticLineage', 'PlanetaryTerraform', 'DoomsdayVault'] },
]
